# Pytorch_Day1_2
- 주요 내용
    - Autgrade란 무엇이며 어떻게 사용하는 지를 확인한다.
        - Autograde의 기능은 특정 함수 식에서 그래디언트 값을 구하는 것이다. 이는 뉴럴 네트워크의 backword와 같다.

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
y.grad_fn

In [5]:
z = y * y * 3
out = z.mean()

In [6]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [7]:
out.backward()

In [8]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [9]:
y.grad

In [10]:
z.grad