# Pytorch_Day1_1
- What is pytorch
    - Numpy가 gpu를 사용
- 주요 내용
    - pytorch의 행열을 만드는 법과 간단한 연산을 배운다.
    - pytorch의 행열 연산과 numpy의 행열 연산을 비교하고 차이점을 본다.
    - pytorch의 행열을 GPU에 업로드 해본다.

In [1]:
import torch

In [2]:
torch.empty(5, 3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.7937e-43, 0.0000e+00],
        [0.0000e+00, 9.5989e-43, 0.0000e+00]])

In [3]:
torch.rand(5,3)

tensor([[0.3001, 0.9136, 0.3889],
        [0.5221, 0.9327, 0.0929],
        [0.1559, 0.8833, 0.0715],
        [0.0425, 0.9028, 0.5876],
        [0.1988, 0.5307, 0.6045]])

In [4]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.zeros(5,3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
torch.Tensor([1, 2])

tensor([1., 2.])

In [7]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.ones(3, 3).size()

torch.Size([3, 3])

In [9]:
x = torch.rand(3, 3)
x

tensor([[0.0533, 0.0119, 0.0150],
        [0.7794, 0.2928, 0.6467],
        [0.6300, 0.0113, 0.9831]])

In [10]:
x[0,0]

tensor(0.0533)

In [11]:
x[0, :]

tensor([0.0533, 0.0119, 0.0150])

In [12]:
x[:, 0]

tensor([0.0533, 0.7794, 0.6300])

In [13]:
x[0, 1]

tensor(0.0119)

In [14]:
x[1, :]

tensor([0.7794, 0.2928, 0.6467])

In [15]:
x[1:, :]

tensor([[0.7794, 0.2928, 0.6467],
        [0.6300, 0.0113, 0.9831]])

In [16]:
x[:, 1:2]

tensor([[0.0119],
        [0.2928],
        [0.0113]])

In [17]:
x[:-2, :]

tensor([[0.0533, 0.0119, 0.0150]])

In [18]:
x[:, -1].size()

torch.Size([3])

In [19]:
x[:, -1:].size()

torch.Size([3, 1])

In [20]:
x[-2:, :-1]

tensor([[0.7794, 0.2928],
        [0.6300, 0.0113]])

In [21]:
x=torch.rand(20)
x.view(2,10).size()

torch.Size([2, 10])

In [22]:
x.view(1,2,10).size()

torch.Size([1, 2, 10])

In [23]:
x.view(2,2,5).size()

torch.Size([2, 2, 5])

In [24]:
devide = torch.device('cuda')

In [25]:
y = torch.rand(3, 3).to(devide)

In [64]:
import numpy as np
temp = [_ for _ in range(0, 100000)]

In [65]:
x = np.array(temp)
x = np.array(temp)
z = np.zeros_like(x)
%timeit for i in range(100000): z[i] = x[i] + y[i]

10 loops, best of 3: 28.6 ms per loop


In [66]:
device = torch.device('cuda')
x_t = torch.Tensor(temp).to(device)
y_t = torch.Tensor(temp).to(device)
z_t = torch.Tensor(temp).to(device)
%timeit for i in range(100000): z_t[i] = x_t[i] + y_t[i]

1 loop, best of 3: 15.2 s per loop
