# Pytorch_Day1_3
- 주요 내용
    - pytorch의 신경망 패키지인 torch.nn을 사용한다.
    - 

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [5]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [6]:
net = Net()
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [144]:
class NN(nn.Module):
    def __init__(self):
        super(NN, self).__init__()
        self.n1  = nn.Linear(3, 1)
    
    def forward(self, x):
        x = self.n1(x)
        return x

In [145]:
nn_net = NN()
nn_net

NN(
  (n1): Linear(in_features=3, out_features=1, bias=True)
)

In [146]:
list(nn_net.parameters())

[Parameter containing:
 tensor([[ 0.2699,  0.2346, -0.0139]], requires_grad=True),
 Parameter containing:
 tensor([0.0062], requires_grad=True)]

In [147]:
in_p = torch.randn(1, 3)
nn_net(in_p)

tensor([[0.5224]], grad_fn=<AddmmBackward>)

In [160]:
m = nn.Conv1d(3, 4, 2, stride=3)
input = torch.randn(1, 3, 4)
m(input).size()

torch.Size([1, 4, 1])

In [175]:
m2 = nn.Linear(2, 3)
m2(torch.randn(1, 2, 2)).size()

torch.Size([1, 2, 3])

In [225]:
class CNN1D(nn.Module):
    def __init__(self):
        super(CNN1D, self).__init__()
        self.n1 = nn.Conv1d(3, 3, 2, stride=1) # in size = 1, 3, detail => out size = 1, 
        self.n2 = nn.Linear(3, 1)
    
    def forward(self, x):
        print(x)
        x = self.n1(x)
        print(x)
        x = self.n2(x)
        print(x)
        return x

In [229]:
cnn1d = CNN1D()
cnn1d(torch.randn(1, 3, 4))

tensor([[[ 0.4357, -0.8233, -0.7080, -0.2840],
         [ 0.9783,  0.0072,  0.0110, -0.8477],
         [-0.7495,  1.3963,  1.2906, -0.4996]]])
tensor([[[ 0.2721, -0.3404, -0.4177],
         [ 0.9219, -0.6342, -0.4521],
         [-0.0814,  0.0165, -0.5219]]], grad_fn=<SqueezeBackward1>)
tensor([[[0.2241],
         [0.1969],
         [0.2847]]], grad_fn=<AddBackward0>)


tensor([[[0.2241],
         [0.1969],
         [0.2847]]], grad_fn=<AddBackward0>)

In [232]:
output = cnn1d(torch.rand(1, 3, 4))
tartget = torch.rand(1, 3, 4)
criterion = nn.MSELoss()
loss = criterion(output, tartget)
loss

tensor([[[0.1195, 0.4485, 0.0956, 0.5480],
         [0.4441, 0.8259, 0.0165, 0.3777],
         [0.2503, 0.5463, 0.7814, 0.8891]]])
tensor([[[-0.0369,  0.0185, -0.1713],
         [ 0.2185,  0.2945, -0.1946],
         [ 0.4480,  0.2866,  0.3508]]], grad_fn=<SqueezeBackward1>)
tensor([[[ 0.1384],
         [ 0.1231],
         [-0.1161]]], grad_fn=<AddBackward0>)


tensor(0.4085, grad_fn=<MseLossBackward>)

In [235]:
output = cnn1d(torch.rand(1, 3, 4))
tartget = torch.rand(1, 3, 4)
criterion = nn.MSELoss()
loss = criterion(output, tartget)

loss.backward()
import torch.optim as optim
print(list(cnn1d.parameters()))
optimizer = optim.SGD(cnn1d.parameters(), lr=0.01)
optimizer.step()
print(list(cnn1d.parameters()))

tensor([[[0.4742, 0.4546, 0.4372, 0.6813],
         [0.4590, 0.3041, 0.5461, 0.4858],
         [0.6617, 0.5733, 0.6932, 0.2056]]])
tensor([[[-0.1112, -0.1387, -0.1180],
         [ 0.1272,  0.1164,  0.1411],
         [ 0.3265,  0.3475,  0.4263]]], grad_fn=<SqueezeBackward1>)
tensor([[[ 0.1586],
         [ 0.0357],
         [-0.0946]]], grad_fn=<AddBackward0>)
[Parameter containing:
tensor([[[-0.0672,  0.1349],
         [ 0.2618, -0.0743],
         [-0.2065,  0.1159]],

        [[ 0.3385, -0.1586],
         [ 0.2567,  0.0471],
         [-0.4062, -0.1206]],

        [[-0.0889,  0.3866],
         [ 0.3892,  0.3007],
         [ 0.1605,  0.2304]]], requires_grad=True), Parameter containing:
tensor([-0.1681,  0.2445, -0.3154], requires_grad=True), Parameter containing:
tensor([[-0.0660, -0.0154, -0.3984]], requires_grad=True), Parameter containing:
tensor([0.1021], requires_grad=True)]
[Parameter containing:
tensor([[[-0.0698,  0.1326],
         [ 0.2592, -0.0771],
         [-0.2082,  0.1139]